### ISSUE TITLE
TypeError: _this.emit is not a function

### ISSUE THREAD

**Issue by musha34** [appium/appium-for-mac#56]
Trying to connect Appium to osx app, such as  /Applications/Messages.app
mac OS 12.14, Appium server  v1.13.0

{
  "deviceName": "Mac",
  "platformName": "Mac",
  "platformVersion": "12.14",
  "otherApps": "/Applications/Messages.app",
  "app": "/Applications/Messages.app"
}

Got below Error from Appium console log:

[BaseDriver] Event 'newSessionStarted' logged at 1558055360914 (18:09:20 GMT-0700 (PDT))
[MJSONWP] Encountered internal error running command: TypeError: _this.emit is not a function
[MJSONWP]     at emit (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-mac-driver/lib/appium-for-mac.js:65:12)
[MJSONWP]     at Generator.throw ()
[MJSONWP]     at asyncGeneratorStep (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
[MJSONWP]     at _throw (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/@babel/runtime/helpers/asyncToGenerator.js:29:9)
[MJSONWP]     at run (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/core-js/modules/es6.promise.js:75:22)
[MJSONWP]     at /Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/core-js/modules/es6.promise.js:92:30
[MJSONWP]     at flush (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/core-js/modules/_microtask.js:18:9)
[MJSONWP]     at process._tickCallback (internal/process/next_tick.js:61:11)

**Comment by Jiurong-Yang** [comment]
This looks like an error in the Appium Mac driver 
https://github.com/appium/appium-mac-driver
