### ISSUE TITLE
Unable to perform click on element with tag AXCell

### ISSUE THREAD

**Issue by harishk5** [appium/appium-for-mac#89]
Element of tag ‘AXCell’ is not responding to click() method and throws WebDriver exception  

Element is completely accessible and other WebElement interaction methods such as ‘isDisplayed’ or ‘getText’ are returning appropriate information.

**Sample Element locator string:**
``/AXApplication[@AXTitle='Hello']/AXWindow[@AXTitle='Window' and @AXIdentifier='_NS:12' and @AXSubrole='AXStandardWindow']/AXGroup[0]/AXScrollArea[@AXIdentifier='_NS:11']/AXOutline[@AXIdentifier='_NS:17']/AXRow[@AXSubrole='AXOutlineRow']/AXCell[0]``

**Console Error:**
```org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 0 milliseconds
Build info: version: ‘3.141.59’, revision: ‘e82be7d358’, time: ‘2018-11-14T08:17:03’
System info: os.name: ‘Mac OS X’, os.arch: ‘x86_64’, os.version: ‘10.14.6’, java.version: ‘11.0.4’
Driver info: io.appium.java_client.AppiumDriver
Capabilities {browserName: Mac, databaseEnabled: false, javascriptEnabled: true, locationContextEnabled: false, nativeEvents: true, platform: MAC, platformName: Mac, takesScreenshot: true, version: 10.14.6, webStorageEnabled: false}
Session ID: tg28AIka
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:214)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:166)
	at org.openqa.selenium.remote.http.JsonHttpResponseCodec.reconstructValue(JsonHttpResponseCodec.java:40)
	at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:80)
	at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:44)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:239)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:41)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:285)
	at org.openqa.selenium.remote.RemoteWebElement.click(RemoteWebElement.java:84)
	at StepDefinitions.MyStepdefs.openTheUrgentItems(MyStepdefs.java:100)
	at ✽.And open the urgent items(/Users/IdeaProjects/iOS/src/main/java/Features/Hello_MacDesktop_Demo.feature:20)```

**Comment by MarwanAbuAssi** [comment]
Any workaround for this issue?
